/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.switstack.switcloud.switcloudl3api.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: password,client_credentials
 */
@Serializable
enum class Oauth2GrantType(val value: String) {

    @SerialName(value = "password")
    password("password"),

    @SerialName(value = "client_credentials")
    client_credentials("client_credentials");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): String? = if (data is Oauth2GrantType) "$data" else null

        /**
         * Returns a valid [Oauth2GrantType] for [data], null otherwise.
         */
        fun decode(data: Any?): Oauth2GrantType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


