/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.switstack.switcloud.switcloudl3api.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


/**
 * 
 *
 * Values: UNDEFINED,APPROVED,DECLINED,ONLINE_REQUEST,END_APPLICATION,SELECT_NEXT,TRY_ANOTHER_INTERFACE,TRY_AGAIN,NA
 */
@Serializable
enum class OutcomeStatus(val value: String) {

    @SerialName(value = "UNDEFINED")
    UNDEFINED("UNDEFINED"),

    @SerialName(value = "APPROVED")
    APPROVED("APPROVED"),

    @SerialName(value = "DECLINED")
    DECLINED("DECLINED"),

    @SerialName(value = "ONLINE_REQUEST")
    ONLINE_REQUEST("ONLINE_REQUEST"),

    @SerialName(value = "END_APPLICATION")
    END_APPLICATION("END_APPLICATION"),

    @SerialName(value = "SELECT_NEXT")
    SELECT_NEXT("SELECT_NEXT"),

    @SerialName(value = "TRY_ANOTHER_INTERFACE")
    TRY_ANOTHER_INTERFACE("TRY_ANOTHER_INTERFACE"),

    @SerialName(value = "TRY_AGAIN")
    TRY_AGAIN("TRY_AGAIN"),

    @SerialName(value = "NA")
    NA("NA");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: Any?): String? = if (data is OutcomeStatus) "$data" else null

        /**
         * Returns a valid [OutcomeStatus] for [data], null otherwise.
         */
        fun decode(data: Any?): OutcomeStatus? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


