/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.switstack.switcloud.switcloudl3api.model

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.util.UUID

/**
 * 
 *
 * @param id 
 * @param organizationId 
 * @param poiId 
 * @param poiConfigId 
 * @param logDataSetId 
 * @param state 
 * @param outcomeStatus 
 * @param trd 
 * @param authorization 
 * @param completion 
 * @param pinBlock 
 */
@Serializable

data class PaymentReadSchema (

    @Contextual @SerialName(value = "id")
    val id: UUID,

    @Contextual @SerialName(value = "organization_id")
    val organizationId: UUID,

    @Contextual @SerialName(value = "poi_id")
    val poiId: UUID,

    @Contextual @SerialName(value = "poi_config_id")
    val poiConfigId: UUID,

    @Contextual @SerialName(value = "log_data_set_id")
    val logDataSetId: UUID,

    @Contextual @SerialName(value = "state")
    val state: State? = null,

    @Contextual @SerialName(value = "outcome_status")
    val outcomeStatus: OutcomeStatus? = null,

    @SerialName(value = "trd")
    val trd: String? = null,

    @SerialName(value = "authorization")
    val authorization: String? = null,

    @SerialName(value = "completion")
    val completion: String? = null,

    @SerialName(value = "pin_block")
    val pinBlock: String? = null

) {


}

