/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.switstack.switcloud.switcloudl3api.model


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param tokenType 
 * @param accessToken 
 * @param expiresIn 
 * @param refreshToken 
 * @param refreshExpiresIn 
 */
@Serializable

data class TokenSchema (

    @SerialName(value = "token_type")
    val tokenType: TokenType,

    @SerialName(value = "access_token")
    val accessToken: String,

    @SerialName(value = "expires_in")
    val expiresIn: Int? = 300,

    @SerialName(value = "refresh_token")
    val refreshToken: String? = null,

    @SerialName(value = "refresh_expires_in")
    val refreshExpiresIn: Int? = 1800

) {

    /**
     * 
     *
     * Values: Bearer
     */
    @Serializable
    enum class TokenType(val value: String) {
        @SerialName(value = "Bearer") Bearer("Bearer");
    }

}

