/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.switstack.switcloud.switcloudl3api.api

import io.switstack.switcloud.switcloudl3api.model.Oauth2GrantType
import io.switstack.switcloud.switcloudl3api.model.TokenSchema
import okhttp3.Call
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.PartConfig
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.Success
import java.io.IOException

class AuthApi(basePath: String = defaultBasePath, client: Call.Factory = defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(baseUrlKey, "http://localhost")
        }
    }

    /**
     * POST /auth/token
     * Token
     *
     * @param grantType
     * @param username  (optional)
     * @param password  (optional)
     * @param clientId  (optional)
     * @param clientSecret  (optional)
     * @return TokenSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun token(grantType: Oauth2GrantType, username: String? = null, password: String? = null, clientId: String? = null, clientSecret: String? = null): TokenSchema {
        val localVarResponse = tokenWithHttpInfo(grantType = grantType, username = username, password = password, clientId = clientId, clientSecret = clientSecret)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as TokenSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }

            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /auth/token
     * Token
     *
     * @param grantType
     * @param username  (optional)
     * @param password  (optional)
     * @param clientId  (optional)
     * @param clientSecret  (optional)
     * @return ApiResponse<TokenSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun tokenWithHttpInfo(grantType: Oauth2GrantType, username: String?, password: String?, clientId: String?, clientSecret: String?): ApiResponse<TokenSchema?> {
        val localVariableConfig = tokenRequestConfig(grantType = grantType, username = username, password = password, clientId = clientId, clientSecret = clientSecret)

        return request<Map<String, PartConfig<*>>, TokenSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation token
     *
     * @param grantType
     * @param username  (optional)
     * @param password  (optional)
     * @param clientId  (optional)
     * @param clientSecret  (optional)
     * @return RequestConfig
     */
    fun tokenRequestConfig(grantType: Oauth2GrantType, username: String?, password: String?, clientId: String?, clientSecret: String?): RequestConfig<Map<String, PartConfig<*>>> {
        val localVariableBody = listOfNotNull(
            "grant_type" to PartConfig(body = grantType, headers = mutableMapOf()),
            if (username != null) "username" to PartConfig(body = username, headers = mutableMapOf()) else null,
            if (password != null) "password" to PartConfig(body = password, headers = mutableMapOf()) else null,
            if (clientId != null) "client_id" to PartConfig(body = clientId, headers = mutableMapOf()) else null,
            if (clientSecret != null) "client_secret" to PartConfig(body = clientSecret, headers = mutableMapOf()) else null
        ).toMap()

        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf("Content-Type" to "application/x-www-form-urlencoded")
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/auth/token",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }
}
