/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package io.switstack.switcloud.switcloudl3api.api

import io.switstack.switcloud.switcloudl3api.model.PaymentCreateSchema
import io.switstack.switcloud.switcloudl3api.model.PaymentReadSchema
import okhttp3.Call
import org.openapitools.client.infrastructure.ApiClient
import org.openapitools.client.infrastructure.ApiResponse
import org.openapitools.client.infrastructure.ClientError
import org.openapitools.client.infrastructure.ClientException
import org.openapitools.client.infrastructure.MultiValueMap
import org.openapitools.client.infrastructure.RequestConfig
import org.openapitools.client.infrastructure.RequestMethod
import org.openapitools.client.infrastructure.ResponseType
import org.openapitools.client.infrastructure.ServerError
import org.openapitools.client.infrastructure.ServerException
import org.openapitools.client.infrastructure.Success
import java.io.IOException

open class PaymentApi(basePath: String = defaultBasePath, client: Call.Factory = defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(BASE_URL_KEY, "http://localhost")
        }
    }

    /**
     * POST /api/payment/payments
     * Create Payment
     * 
     * @param paymentCreateSchema 
     * @return PaymentReadSchema
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createPayment(paymentCreateSchema: PaymentCreateSchema) : PaymentReadSchema {
        val localVarResponse = createPaymentWithHttpInfo(paymentCreateSchema = paymentCreateSchema)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PaymentReadSchema
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /api/payment/payments
     * Create Payment
     * 
     * @param paymentCreateSchema 
     * @return ApiResponse<PaymentReadSchema?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createPaymentWithHttpInfo(paymentCreateSchema: PaymentCreateSchema) : ApiResponse<PaymentReadSchema?> {
        val localVariableConfig = createPaymentRequestConfig(paymentCreateSchema = paymentCreateSchema)

        return request<PaymentCreateSchema, PaymentReadSchema>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createPayment
     *
     * @param paymentCreateSchema 
     * @return RequestConfig
     */
    fun createPaymentRequestConfig(paymentCreateSchema: PaymentCreateSchema) : RequestConfig<PaymentCreateSchema> {
        val localVariableBody = paymentCreateSchema
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/api/payment/payments",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }



}
